apiVersion: tekton.dev/v1beta1
kind: TriggerTemplate
metadata:
  name: template
spec:
  params:
    - name: Cloud_Api_key
      description: This is cloud api key
    - name: User_Name
      description: User Name
    - name: Pwd
      description: Password
  resourcetemplates:
    - apiVersion: v1
      kind: PersistentVolumeClaim
      metadata:
        name: pipelinerun-$(uid)-pvc
      spec:
        resources:
          requests:
            storage:  5Gi
        volumeMode: Filesystem
        accessModes:
          - ReadWriteOnce
    - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun
      metadata:
        name: pipelinerun-$(uid)
      spec:
        pipelineRef:
            name: pipeline
        workspaces:
          - name: pipeline-pvc
            persistentVolumeClaim:
              claimName: pipelinerun-$(uid)-pvc
        - name: Cloud_Api_key
          value: $(params.Cloud_Api_key)
        - name: User_Name
          value: $(params.User_Name)
        - name: Pwd
          value: $(params.Pwd)        
---
apiVersion: tekton.dev/v1beta1
kind: TriggerBinding
metadata:
  name: binding
spec:
  params:
    - name: Cloud_Api_key
      value: $(params.Cloud_Api_key)
    - name: User_Name
      value: $(params.User_Name)
    - name: Pwd
      value: $(params.Pwd)
---
apiVersion: tekton.dev/v1beta1
kind: EventListener
metadata:
  name: listener
spec:
  triggers:
    - binding:
        name: binding
      template:
        name: template
