apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: pipeline
spec:
  workspaces:
  - name: pipeline-pvc
  tasks:
    - name: echo-hello-world
      image: ubuntu
      script: |
        #!/usr/bin/env bash
        set -xe
        echo "Hello World!"
      
      workspaces:
      - name: task-pvc
        workspace: pipeline-pvc  
