apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: build-task
spec:
  workspaces:
  - name: task-pvc
    mountPath: /artifacts   
  steps:
    - name: echo-hello-world
      image: ubuntu
      script: |
        #!/usr/bin/env bash
        set -xe
        echo "Hello World!"

      
