apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: echo-hello-world
spec:
  workspaces:
  - name: task-pvc
    mountPath: /artifacts   
  steps:
    - name: echo-hello-world
      image: ubuntu
      script: |
        #!/usr/bin/env bash
        set -xe
        echo "This is krishna"
        ibmcloud resource service-instance-delete mas-keyprotect
        echo "mas-keyprotect deleted"

      
