apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: build-task
spec:
  workspaces:
  - name: task-pvc
    mountPath: /artifacts   
  steps:
    - name: echo-hello-world
      image: alpine/git
      env:
        - name: REPOSITORY
          value: https://github.com/krishna1231/teckton-sh.git
        - name: REVISION
          value: master
      command: ["/bin/sh", "-c"]
      args:
        - set -e -o pipefail;
          echo "Cloning $REPOSITORY";
          cd /workspace && git clone -q -b master https://github.com/krishna1231/teckton-sh.git .;
    

      
